kind: pipeline
type: docker
name: default

environment:
  DEPENDENCIES: libudev-dev

steps:
  - name: test
    image: rust:bullseye
    pull: always
    commands:
      - apt-get update -qq
      - apt-get install -qqy $DEPENDENCIES
      - rustup component add clippy rustfmt
      - cargo fmt --check
      - cargo test
      - cargo clippy
  - name: release
    image: rust:bullseye
    pull: always
    commands:
      - apt-get update -qq
      - apt-get install -qqy $DEPENDENCIES
      - cargo publish
    when:
      ref:
        - refs/tags/v*
    environment:
      CARGO_REGISTRY_TOKEN:
        from_secret: cargo_registry_token
  - name: discord notification
    image: appleboy/drone-discord
    when:
      status: [success, failure]
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      tts: true
      message: >
        {{#success build.status}}
          {{repo.name}} build {{build.number}} succeeded: <{{build.link}}>
        {{else}}
          {{repo.name}} build {{build.number}} failed: <{{build.link}}>
        {{/success}}
